---
title: International Catholic Community Heidelberg
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: infoheidelberg@internationalcatholiccommunity.com
description: |
  Our English-speaking Catholic Community was born in 2013. We celebrate Mass in English, in the Church of St. Michael every Sunday at 1 pm.
  Our community is made up of employees of different international companies, people engaged in studies and research at the university, and guests in this city.
baseurl: "/site"
url: http://www.heidelberg-community.internationalcatholiccommunity.com
assets: assets
exclude:
- node_modules
markdown: kramdown
gallery:
  dir: assets/gallery
  symlink: false
  title: Photo Gallery
  sort_field: date_time
  thumbnail_size:
    x: 400
    y: 400
gems:
- jekyll-gallery-generator
