# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: International Catholic Community Heidelberg
email: infoheidelberg@internationalcatholiccommunity.com
description: >
    Our English-speaking Catholic Community was born in 2013. We celebrate Mass
    in English, in the Church of St. Michael every Sunday at 1 pm.

    Our community
    is made up of employees of different international companies, people engaged in
    studies and research at the university, and guests in this city.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.heidelberg-community.internationalcatholiccommunity.com"
# twitter_username: icch
# github_username:  icch
assets: "/assets/"
exclude: ["node_modules"]

# Build settings
markdown: kramdown

gallery:
    dir: assets/gallery
    symlink: false
    title: "Photo Gallery"
    sort_field: "date_time"

    thumbnail_size:
        x: 400
        y: 400

gems:
- jekyll-gallery-generator
